### ISSUE TITLE
Solids file for case

### ISSUE THREAD

**Issue by grayzu** [CNCKitchen/PrusaDUET#1]
@CNCKitchen  Thanks for sharing this code, the video and the blog post!! I have run into the exact same problem as u with my bed heater frying the connector on my Prusa MMk2.5 so plan to follow your lead and upgrade to the Duet 3 Mini 5+. The board should actually arrive today. 

Anyway, the main difference between my build and yours is that I have the bear frame instead of the stock frame. I would like to use the case that I made for the mini but need to tweak it to fit the bear. Any chance you can share the Fusion file or step file here?

Thanks in advance!

**Comment by CNCKitchen** [comment]
Should be all there now!
